---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*
    - lib/generators/smart_listing/templates/*.rb

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/ArgumentsForwarding:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 155

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false

###########
# METRICS #
###########

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

#########
# RSPEC #
#########

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  Max: 4

RSpec/MetadataStyle:
  EnforcedStyle: hash

############
# CAPYBARA #
############

Capybara/NegationMatcher:
  EnforcedStyle: not_to

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: strict
